[workspace]
name = "template"
description = "This is the example project"
authors = ["maximlt", "jlstevens"]
version = "2022-01-20"
channels = ["https://repo.anaconda.com/pkgs/main", "https://repo.anaconda.com/pkgs/r", "https://repo.anaconda.com/pkgs/msys2"]
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]

[dependencies]
notebook = ">=6.5.2,<7"
python = "3.11.*"
panel = ">=1.4.2"
hvplot = ">=0.10.0"
pandas = ">=2.2.1"
pip = "*"
setuptools = "*"
wheel = "*"

[target.osx-arm64.dependencies]
libgfortran = "*"

[tasks.notebook]
cmd = "jupyter notebook template.ipynb"
depends-on = ["download"]

[tasks.dashboard]
cmd = "panel serve --rest-session-info --session-history -1 template.ipynb"
depends-on = ["download"]

[tasks.download]
cmd = "mkdir -p data && curl -fsSL -o data/penguins.csv https://datasets.holoviz.org/penguins/v1/penguins.csv"
outputs = ["data/penguins.csv"]
