[workspace]
name = "particle_swarms"
channels = ["main", "msys2"]
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]

[tool.metadata]
created = "2020-08-10"
maintainers = ["scottire"]
categories = ["Mathematics"]
labels = ["holoviews", "bokeh", "panel"]
description = "Interactive dashboard for Particle Swarm Optimisation"
no_data_ingestion = true

[dependencies]
python = "3.9.*"
notebook = "*"
holoviews = "*"
panel = "*"
param = "*"
numpy = "*"
pandas = "*"
bokeh = "*"
pip = "*"  # promoted from anaconda-project lock
setuptools = "*"  # promoted from anaconda-project lock
wheel = "*"  # promoted from anaconda-project lock

[target.osx-arm64.dependencies]
libgfortran = "*"  # promoted from anaconda-project lock

[tasks]
dashboard = "panel serve --rest-session-info --session-history -1 particle_swarms.ipynb --show"
notebook = "jupyter notebook particle_swarms.ipynb"
