[workspace]
name = "gull_tracking"
channels = ["main", "msys2"]
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]

[tool.metadata]
created = "2019-12-12"
maintainers = ["jbednar"]
categories = ["Other Sciences", "Geospatial"]
labels = ["datashader", "hvplot", "bokeh"]
description = "Visualizing GPS tracking for herring gulls in Belgium"

[dependencies]
python = "3.11.*"
bokeh = ">=3.3.4"
notebook = ">=6.5.4,<7"
colorcet = ">=3.1.0"
datashader = ">=0.16.0"
hvplot = ">=0.10.0"
pandas = ">=2.2.1"
pip = "*"
setuptools = "*"
wheel = "*"

[target.osx-64.dependencies]
libgfortran = "*"

[target.osx-arm64.dependencies]
libgfortran = "*"

[tasks.notebook]
cmd = "jupyter notebook gull_tracking.ipynb"
depends-on = ["download"]

[tasks.download]
env = { FILENAME = "data/HG_OOSTENDE-gps-2018.csv" }
cmd = "mkdir -p data && curl -fsSL -o $FILENAME https://s3.eu-west-1.amazonaws.com/datasets.holoviz.org/HG_OOSTENDE/v1/HG_OOSTENDE-gps-2018.csv"
outputs = ["data/HG_OOSTENDE-gps-2018.csv"]
