[workspace]
name = "landsat_clustering"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]

[tool.metadata]
created = "2018-11-26"
maintainers = ["TomAugspurger", "jbednar"]
categories = ["Geospatial"]
labels = ["datashader", "holoviews", "bokeh", "dask", "dask-ml"]
description = "Example of spectral clustering landsat data"

[dependencies]
python = "3.10.*"
notebook = "*"
pyepsg = "*"
cartopy = "*"
datashader = "*"
fastparquet = "*"
geoviews = "*"
holoviews = "*"
python-snappy = "*"
intake = "*"
intake-xarray = "*"
rioxarray = "*"
rasterio = "*"
msgpack-python = "*"
dask = "*"
s3fs = "*"
pandas = "*"
param = "*"
poppler = "*"
distributed = "*"
tbb = "*"
dask-ml = "*"
pip = "*"  # promoted from anaconda-project lock
wheel = "*"  # promoted from anaconda-project lock

[activation.env]
INTAKE_CACHE_DIR = "data"

[tasks]
notebook = "jupyter notebook landsat_clustering.ipynb"
