[workspace]
name = "landsat"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]

[tool.metadata]
created = "2016-06-20"
maintainers = ["jbednar"]
categories = ["Geospatial"]
labels = ["geoviews", "holoviews", "bokeh", "datashader", "numba", "xarray"]
description = "Datashading LandSat8 raster satellite imagery"

[dependencies]
python = "*"
notebook = "*"
bokeh = "*"
cartopy = "*"
datashader = "*"
geoviews = "*"
holoviews = "*"
numpy = "*"
pandas = "*"
rasterio = "*"
xarray = "*"
numba = "*"
param = "*"
rioxarray = "*"
jupyter_client = "<8"
pip = "*"
wheel = "*"

[tasks.notebook]
cmd = "jupyter notebook landsat.ipynb"
depends-on = ["download"]

[tasks.download]
env = { FILENAME = "data" }
cmd = "mkdir -p $FILENAME && curl -fsSL -o .DATA.zip http://s3.amazonaws.com/datashader-data/mobile_landsat8.zip && python -m zipfile -e .DATA.zip $FILENAME && rm .DATA.zip"
outputs = ["data"]
