[workspace]
name = "gene_profiling"
description = "Explore single-cell populations by linking cluster visualization with marker gene expression analysis"
authors = ["droumis"]
version = "2025-09-12"
channels = ["conda-forge", "nodefaults"]
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]

[dependencies]
notebook = ">=6.5.2,<7"
python = "3.11.*"
numpy = ">=2.2.6"
datashader = ">=0.18.2"
bokeh = ">=3.8.0"
anndata = ">=0.12.2"
scanpy = ">=1.11.4"
Markdown = "*"
pip = "*"
wheel = "*"

[pypi-dependencies]
hv-anndata = ">=v0.0.3a2"
holoviews = ">=v1.22.0a0"

[tasks]
lab = "jupyter lab gene_profiling.ipynb"
notebook = "jupyter notebook gene_profiling.ipynb"
dashboard = "panel serve --rest-session-info --session-history -1 gene_profiling.ipynb --show"
