# Composite action used by the build and build_all workflows.
name: build_one
description: Build
inputs:
  project:
    # Could be a list of the available projects to make it easier to select one
    description: Project to build
    required: true
  target:
    description: Build mode
    required: true
    default: dryrun
  gh_token:
    description: GitHub Token
    required: true

runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
    - uses: hmarr/debug-action@v2
    - name: conda setup
      shell: bash -l {0}
      run: |
        conda install -c pyviz "pyctdev>=0.5"
        doit ecosystem_setup
    - name: archive project
      shell: bash -l {0}
      run: |
        doit archive_project:${{ inputs.project }}
    - name: move thumbnails
      shell: bash -l {0}
      run: |
        doit move_thumbnails:${{ inputs.project }}
    - name: prepare project
      shell: bash -l {0}
      run: |
        doit prepare_project:${{ inputs.project }}
    - name: run notebooks
      shell: bash -l {0}
      run: |
        doit run_notebooks:${{ inputs.project }}
    - name: deploy project
      shell: bash -l {0}
      # Deploy only when the target is 'evaluated' on workflow_dispatch, or on push
      if: (github.event_name == 'workflow_dispatch' && inputs.target == 'evaluated') || github.event_name == 'push'
      run: |
        DIR=${{ inputs.project }}
        git config user.email "travis@travis.org"
        git config user.name "travis"
        mv ./doc/$DIR ./tmp
        git fetch https://github.com/${GITHUB_REPOSITORY}.git evaluated:refs/remotes/evaluated
        git diff
        git checkout evaluated || exit 1
        echo 'HERE'
        # if [ -e  ./doc/$DIR ]; then rm -rf ./doc/$DIR; fi
        # mkdir ./doc/$DIR
        # mv ./tmp/* ./doc/$DIR
        # git add ./doc/$DIR
        # git commit -m "adding $DIR"
        # git push -f -q "https://pyviz-developers:${{ inputs.gh_token }}@github.com/pyviz-topics/examples.git" HEAD:evaluated
    - name: clean up
      shell: bash -l {0}
      run: |
        git checkout main
        doit clean archive_project:${{ inputs.project }}
        doit clean move_thumbnails:${{ inputs.project }}
        doit clean prepare_project:${{ inputs.project }}
        doit clean run_notebooks:${{ inputs.project }}
        git diff --quiet --exit-code
