[workspace]
name = "genetic_algorithm"
description = "Interactive dashboard for Genetic Algorithm"
authors = ["scottire"]
version = "2020-07-22"
channels = ["https://repo.anaconda.com/pkgs/main", "https://repo.anaconda.com/pkgs/r", "https://repo.anaconda.com/pkgs/msys2"]
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]

[dependencies]
python = "3.9.*"
notebook = "*"
holoviews = "*"
panel = "*"
numpy = "*"
pandas = "<2.1"
bokeh = "*"
param = "*"
pip = "*"
setuptools = "*"
wheel = "*"

[target.osx-arm64.dependencies]
libgfortran = "*"

[tasks]
dashboard = "panel serve --rest-session-info --session-history -1 genetic_algorithm.ipynb --show"
notebook = "jupyter notebook genetic_algorithm.ipynb"
