[workspace]
name = "gerrymandering"
channels = ["main", "msys2"]
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]

[tool.metadata]
created = "2016-01-01"
maintainers = ["philippjfr", "jbednar"]
categories = ["Geospatial"]
labels = ["datashader", "geoviews", "hvplot", "bokeh", "dask", "geopandas"]
description = "Combine data of very different types to show gerrymandering"

[dependencies]
python = "3.11.*"
notebook = ">=6.5.4,<7"
cartopy = ">=0.21.1"
dask = ">=2023.6.0"
datashader = ">=0.16.0"
geoviews = ">=1.11.1"
holoviews = ">=1.18.3"
pandas = ">=2.1.1"
hvplot = ">=0.10.0"
geopandas = ">=0.14.2"
pyarrow = ">=14"
pip = "*"  # promoted from anaconda-project lock
wheel = "*"  # promoted from anaconda-project lock

[target.osx-64.dependencies]
libgfortran = "*"  # promoted from anaconda-project lock

[target.osx-arm64.dependencies]
libgfortran = "*"  # promoted from anaconda-project lock

[tasks.notebook]
cmd = "jupyter notebook gerrymandering.ipynb"
depends-on = ["download"]

[tasks.download]
depends-on = ["download-census_data", "download-congressional_district_data"]

[tasks.download-census_data]
env = { FILENAME = "data/census.snappy.parq" }
cmd = "mkdir -p $FILENAME && curl -fsSL -o .census_data.zip http://s3.amazonaws.com/datashader-data/census.snappy.parq.zip && python -m zipfile -e .census_data.zip $FILENAME && rm .census_data.zip"
outputs = ["data/census.snappy.parq"]

[tasks.download-congressional_district_data]
env = { FILENAME = "data/congressional_districts" }
cmd = "mkdir -p $FILENAME && curl -fsSL -o .congressional_district_data.zip https://s3.amazonaws.com/datashader-data/cb_2015_us_cd114_5m.zip && python -m zipfile -e .congressional_district_data.zip $FILENAME && rm .congressional_district_data.zip"
outputs = ["data/congressional_districts"]
