name: build_all

on: 
  workflow_dispatch:
    inputs:
      target:
        description: Build mode
        type: choice
        options:
        # - push-to-evaluated
        - dryrun
        required: true
        default: dryrun

jobs:
  build:
    name: Build all the projects in ${{ github.event.inputs.target }} mode
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -l {0} 
    strategy:
      fail-fast: false
      matrix:
        project:
          - boids
          - census
    steps:
    - name: Build project ${{ matrix.project }}
      uses: ./.github/workflows/build.yml
      with:
        target: ${{ github.event.inputs.target }}
        project: ${{ matrix.project }}

    # - name: Trigger downstream test workflow and wait
    #   uses: convictional/trigger-workflow-and-wait@v1.6.3
    #   with:
    #     github_token: ${{ secrets.ACCESS_TOKEN }}
    #     workflow_file_name: build.yaml
    #     ref: main
    #     wait_interval: 120
    #     propagate_failure: true
    #     trigger_workflow: true
    #     wait_workflow: true
