name: test one

on:
  # Make it a reusable workflow
  workflow_call:
    inputs:
      project:
        description: Project to test
        required: true
        type: string
  # Run it from the UI
  workflow_dispatch:
    inputs:
      project:
        description: Project to test
        required: true

jobs:
  test_one:
    name: test ${{ inputs.project }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - uses: prefix-dev/setup-pixi@v0.10.1
        with:
          manifest-path: ${{ inputs.project }}/pixi.toml
          environments: test
          locked: true
      - name: test project
        run: pixi run --manifest-path ${{ inputs.project }}/pixi.toml -e test test
      - name: check clean up
        run: |
          git diff --name-only
          git diff --quiet --exit-code
