# Allows to test multiple projects in a matrix.
# - found out which projects to test
# - if any, test them in a matrix

# This runs on:
# - workflow_call: this is used by pr_flow.yml to test multiple projects
# - workflow_dispatch: to manually trigger tests
# - schedule: once a month for all of them

name: test multiple
on:
  workflow_call:
    inputs:
      projects:
        description: JSON-like list of projects
        type: string
        required: true
      type:
        description: hack
        type: string
        required: true
  workflow_dispatch:
    inputs:
      all:
        description: all the projects
        type: boolean
        default: false
        required: true
      projects:
        description: comma-separated list
        type: string
        required: false
  schedule:
    # 3rd day of the month at 2 (avoiding 1st day that may have more load)
    - cron: "0 2 3 * *"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  inferprojects:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    defaults:
      run:
        shell: bash -l {0}
    outputs:
      projects: ${{ steps.set-projects.outputs.projects }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"
      - name: infer project list
        id: set-projects
        env:
          ALL: ${{ inputs.all }}
          INPUTS: ${{ inputs.projects }}
          TYPE: ${{ inputs.type }}
        run: |
          if [ "$TYPE" == "workflow_call" ]; then
            PROJECTS=$INPUTS
          elif [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
            if [ "$ALL" == "true" ]; then
              PROJECTS=$(python scripts/list_projects.py)
            else
              PROJECTS=$(python scripts/list_projects.py --projects "$INPUTS")
            fi
          elif [ "$GITHUB_EVENT_NAME" == "schedule" ]; then
            PROJECTS=$(python scripts/list_projects.py)
          fi
          echo "Projects: $PROJECTS"
          echo "PROJECTS=$PROJECTS" >> $GITHUB_OUTPUT
  test:
    needs: inferprojects
    if: needs.inferprojects.outputs.projects != '[]'
    name: Test projects
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.inferprojects.outputs.projects) }}
    uses: ./.github/workflows/test_one.yml
    with:
      project: ${{ matrix.project }}
    # secrets: inherit
