name: test one

on:
  # Make it a reusable workflow
  workflow_call:
    inputs:
      project:
        description: Project to test
        required: true
        type: string
  # Run it from the UI
  workflow_dispatch:
    inputs:
      project:
        description: Project to test
        required: true

permissions: {}

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}-${{ inputs.project }}
  cancel-in-progress: true

jobs:
  test_one:
    name: test ${{ inputs.project }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          manifest-path: ${{ inputs.project }}/pixi.toml
          environments: test
          locked: true
      - name: test project
        env:
          PROJECT: ${{ inputs.project }}
        run: pixi run --manifest-path $PROJECT/pixi.toml -e test test
      - name: check clean up
        run: |
          git diff --name-only
          git diff --quiet --exit-code
